In [1]:
import numpy as np
import pandas as pd

import re
import os

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import glob

In [67]:
os.getcwd()

'C:\\Users\\Admin\\jupyter notebook\\12.Data Science And Machine Learning\\1.Supervised Machine Learning\\7.Naive Bayes'

In [68]:
folder_path='C:\\Users\\Admin\\Downloads\\movie_reviews\\'
os.listdir(folder_path)

['negative', 'positive']

In [69]:
pos_folder_path='C:\\Users\\Admin\\Downloads\\movie_reviews\\' + 'positive'
neg_folder_path='C:\\Users\\Admin\\Downloads\\movie_reviews\\' + 'negative'

pos_text_files=glob.glob(f'{pos_folder_path}\\*.txt')
neg_text_files=glob.glob(f'{neg_folder_path}\\*.txt')

In [70]:
len(pos_text_files)

1000

In [71]:
len(neg_text_files)

1000

In [72]:
review_list = []

for file_name in pos_text_files:
    f = open(file_name)
    text = f.read()
    text = re.sub('[^a-zA-Z]+', ' ', text)
    f.close()
#     print(text)
    review_list.append(text)
    
for file_name in neg_text_files:
    f = open(file_name)
    text = f.read()
    text = re.sub('[^a-zA-Z]+', ' ', text)
    f.close()
    review_list.append(text)

In [73]:
len(review_list)

2000

## create Target Column

In [74]:
pos_target=np.ones(len(pos_text_files),dtype=int)
neg_target=np.zeros(len(neg_text_files),dtype=int)

y=np.append(pos_target,neg_target)
y=pd.Series(y) # if we do not want as an array and as an list if we want simple output we do it series
y

0       1
1       1
2       1
3       1
4       1
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Length: 2000, dtype: int32

## Bag Of Words

## Stemming And Lemmetization

## min_df

In [75]:
count_vector=CountVectorizer(stop_words='english',min_df=0.05)
x_cnt_vector=count_vector.fit_transform(review_list)
x=pd.DataFrame(x_cnt_vector.toarray(),columns=count_vector.get_feature_names())
x

C:\Users\Admin\AKSHAY\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ability  able  absolutely  act  acting  action  actor  actors  actress  \
0           0     0           0    0       1       0      0       0        0   
1           0     0           0    0       0       0      0       0        0   
2           0     0           1    0       1       0      0       0        0   
3           0     0           0    5       1       0      0       1        0   
4           0     0           0    0       0       0      0       1        0   
...       ...   ...         ...  ...     ...     ...    ...     ...      ...   
1995        0     0           1    0       0       0      0       0        0   
1996        1     0           0    0       0       0      0       0        0   
1997        1     0           0    1       0       0      1       0        0   
1998        0     0           0    0       0       0      1       0        0   
1999        0     0           0    0       0       0      0       0        0   

      actual  ...  writers  writing  written  wrong  wrote  year  years  yes  \
0          0  ...        0        0        0      0      0     0      0    0   
1          0  ...        0        0        0      0      0     1      0    0   
2          0  ...        0        0        0      0      0     2      0    0   
3          1  ...        0        0        0      0      0     0      1    0   
4          0  ...        0        0        0      0      0     0      0    0   
...      ...  ...      ...      ...      ...    ...    ...   ...    ...  ...   
1995       0  ...        0        0        0      0      0     2      0    1   
1996       0  ...        0        0        0      0      0     1      1    0   
1997       0  ...        0        0        0      0      0     0      0    0   
1998       0  ...        0        0        1      1      0     0      0    0   
1999       0  ...        0        0        0      0      0     0      0    0   

      york  young  
0        0      0  
1        0      0  
2        0      0  
3        1      1  
4        1      0  
...    ...    ...  
1995     0      0  
1996     0      0  
1997     0      0  
1998     0      0  
1999     0      0  

[2000 rows x 886 columns]

In [76]:
print(count_vector.get_feature_names())

['ability', 'able', 'absolutely', 'act', 'acting', 'action', 'actor', 'actors', 'actress', 'actual', 'actually', 'add', 'adds', 'admit', 'age', 'agent', 'ago', 'air', 'alien', 'alive', 'amazing', 'america', 'american', 'amusing', 'annoying', 'apart', 'apparently', 'appear', 'appearance', 'appears', 'approach', 'aren', 'art', 'aside', 'ask', 'asks', 'aspect', 'atmosphere', 'attempt', 'attempts', 'attention', 'audience', 'audiences', 'average', 'away', 'awful', 'baby', 'background', 'bad', 'based', 'basic', 'basically', 'battle', 'beautiful', 'begin', 'beginning', 'begins', 'believable', 'believe', 'ben', 'best', 'better', 'big', 'biggest', 'bit', 'black', 'blood', 'blue', 'body', 'book', 'boring', 'box', 'boy', 'break', 'brief', 'brilliant', 'bring', 'brings', 'british', 'brother', 'brothers', 'brought', 'bruce', 'budget', 'building', 'bunch', 'business', 'called', 'came', 'camera', 'car', 'care', 'career', 'case', 'cast', 'casting', 'caught', 'central', 'century', 'certain', 'certainly

C:\Users\Admin\AKSHAY\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


## TF-IDF Vectorizer

In [85]:
tfidf_vector = TfidfVectorizer(stop_words='english', min_df=0.05)
x_tfidf_vector = tfidf_vector.fit_transform(review_list)
x = pd.DataFrame(x_tfidf_vector.toarray(), columns=tfidf_vector.get_feature_names())
x

C:\Users\Admin\AKSHAY\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ability  able  absolutely       act    acting  action     actor  \
0     0.000000   0.0    0.000000  0.000000  0.050373     0.0  0.000000   
1     0.000000   0.0    0.000000  0.000000  0.000000     0.0  0.000000   
2     0.000000   0.0    0.102356  0.000000  0.068145     0.0  0.000000   
3     0.000000   0.0    0.000000  0.289285  0.042533     0.0  0.000000   
4     0.000000   0.0    0.000000  0.000000  0.000000     0.0  0.000000   
...        ...   ...         ...       ...       ...     ...       ...   
1995  0.000000   0.0    0.051310  0.000000  0.000000     0.0  0.000000   
1996  0.074700   0.0    0.000000  0.000000  0.000000     0.0  0.000000   
1997  0.102257   0.0    0.000000  0.085858  0.000000     0.0  0.069705   
1998  0.000000   0.0    0.000000  0.000000  0.000000     0.0  0.070130   
1999  0.000000   0.0    0.000000  0.000000  0.000000     0.0  0.000000   

        actors  actress    actual  ...  writers  writing  written     wrong  \
0     0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
1     0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
2     0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
3     0.043055      0.0  0.069053  ...      0.0      0.0  0.00000  0.000000   
4     0.054598      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
...        ...      ...       ...  ...      ...      ...      ...       ...   
1995  0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
1996  0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
1997  0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   
1998  0.000000      0.0  0.000000  ...      0.0      0.0  0.07528  0.078095   
1999  0.000000      0.0  0.000000  ...      0.0      0.0  0.00000  0.000000   

      wrote      year     years       yes      york     young  
0       0.0  0.000000  0.000000  0.000000  0.000000  0.000000  
1       0.0  0.044504  0.000000  0.000000  0.000000  0.000000  
2       0.0  0.128293  0.000000  0.000000  0.000000  0.000000  
3       0.0  0.000000  0.040127  0.000000  0.063777  0.043447  
4       0.0  0.000000  0.000000  0.000000  0.080876  0.000000  
...     ...       ...       ...       ...       ...       ...  
1995    0.0  0.064312  0.000000  0.047589  0.000000  0.000000  
1996    0.0  0.043402  0.043500  0.000000  0.000000  0.000000  
1997    0.0  0.000000  0.000000  0.000000  0.000000  0.000000  
1998    0.0  0.000000  0.000000  0.000000  0.000000  0.000000  
1999    0.0  0.000000  0.000000  0.000000  0.000000  0.000000  

[2000 rows x 886 columns]

In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

## Model Training

## 1. Gaussian NB

In [78]:
gnb_model=GaussianNB()
gnb_model.fit(x_train,y_train)

GaussianNB()

In [79]:
y_pred=gnb_model.predict(x_test)

cnf_martix=confusion_matrix(y_test,y_pred)
print('Confusion Matrix:\n',cnf_martix)

acc = accuracy_score(y_test,y_pred)
print('Accuracy Score:', acc)

clf_report = classification_report(y_test,y_pred)
print(' Classification Report:\n', clf_report)

Confusion Matrix:
 [[164  41]
 [ 64 131]]
Accuracy Score: 0.7375
 Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.80      0.76       205
           1       0.76      0.67      0.71       195

    accuracy                           0.74       400
   macro avg       0.74      0.74      0.74       400
weighted avg       0.74      0.74      0.74       400



## 2.Multinomial NB

In [80]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train,y_train)

MultinomialNB()

In [81]:
y_pred = mnb_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print('Confustion Matrix:\n', cnf_matrix)

acc = accuracy_score(y_test,y_pred)
print('Accuracy Score:', acc)

clf_report = classification_report(y_test,y_pred)
print(' Classification Report:\n', clf_report)

Confustion Matrix:
 [[169  36]
 [ 42 153]]
Accuracy Score: 0.805
 Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.82      0.81       205
           1       0.81      0.78      0.80       195

    accuracy                           0.81       400
   macro avg       0.81      0.80      0.80       400
weighted avg       0.81      0.81      0.80       400



## Bernoulli NB

In [82]:
bnb_model = BernoulliNB()
bnb_model.fit(x_train,y_train)

BernoulliNB()

In [83]:
y_pred = bnb_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print('Confustion Matrix:\n', cnf_matrix)

acc = accuracy_score(y_test,y_pred)
print('Accuracy Score:', acc)

clf_report = classification_report(y_test,y_pred)
print(' Classification Report:\n', clf_report)

Confustion Matrix:
 [[169  36]
 [ 51 144]]
Accuracy Score: 0.7825
 Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.82      0.80       205
           1       0.80      0.74      0.77       195

    accuracy                           0.78       400
   macro avg       0.78      0.78      0.78       400
weighted avg       0.78      0.78      0.78       400



In [ ]:
gnb_model=GaussianNB() # for checking parameters